In [7]:
import pandas as pd
import datetime
import numpy as np
import seaborn as sns
import re 

pd.set_option('display.max_colwidth', -1)

Extract Data For February

In [8]:
# Open the file with read only permit
f = open('February raw data.txt')

# use readline() to read the first line 
line = f.readline()
i=0

while line:
    
    line = line.strip()
    line = line.replace('[Source]','')
    p1 = '\d+ new cases in the \w+'
    p2 = '\d+ new cases in \w+'
    p3 = '\d+ new cases and \d+ new deaths in the \w+'
    p4 = '\d+ new cases and \d+ new deaths in \w+'
    p5 = '\d+ new death and \d+ new cases in the \w+'
    p6 = '\d+ new death and \d+ new cases in \w+'
    
    if re.findall('^February',line):
        print('February ', re.findall('[0-9]{1,2}', line)[0])
    elif re.findall(p1, line):
        print(re.split(' new cases in the ', re.findall(p1, line)[0]))
    elif re.findall(p2, line):
        print(re.split(' new cases in ', re.findall(p2, line)[0]))
    elif re.findall(p3, line):
        print(re.split(' new cases and \d+ new deaths in the ', re.findall(p3, line)[0]))
    elif re.findall(p4, line):
        print(re.split('new cases and \d+ new deaths in', re.findall(p4, line)[0]))
    elif re.findall(p5, line):
        newline = re.split(' new death and ', re.findall(p5, line)[0])[1]
        print(re.split(' new cases in the ', newline))
    elif re.findall(p6, line):
        newline = re.split(' new death and ', re.findall(p6, line)[0])[1]
        print(re.split(' new cases in ', newline))
        
    line = f.readline()
    
f.close()

February  28
['2', 'UnitedStates']
['2', 'Norway']
['4', 'UK']
['233 ', ' Italy']
['4', 'Sweden']
['2', 'Austria']
['2', 'Romania']
['11', 'Germany']
['7', 'Switzerland']
['8', 'Spain']
['2', 'Croatia']
['5', 'Bahrain']
['571', 'SouthKorea']
['2', 'Taiwan']
February  27
['3', 'Germany']
['3', 'Norway']
['12', 'Spain']
['3', 'Austria']
['20', 'France']
['5', 'Sweden']
['14', 'Germany']
['180 ', ' Italy']
['2', 'Oman']
['6', 'UnitedArabEmirates']
['2', 'Greece']
['106 ', ' Iran']
['2', 'UK']
['3', 'Singapore']
February  26
['5', 'Germany']
['3', 'UnitedStates']
['2', 'Pakistan']
['3', 'Spain']
['4', 'HongKong']
['44 ', ' Iran']
['14', 'Kuwait']
['3', 'Bahrain']
['3', 'Thailand']
February  25
['2', 'Italy']
['60', 'SouthKorea']
February  24
['2', 'Kuwait']
['18', 'UnitedStates']
['5', 'HongKong']
['2', 'Taiwan']
['3', 'Kuwait']
['366 ', ' Hubei']
February  23
['78', 'Italy']
['166 ', ' SouthKorea']
['14', 'Iran']
['2', 'Taiwan']
['12', 'Japan']
February  22
['2', 'Milan']
['5', 'VÃ²']
['3', 'SouthKorea']
['2', 'UnitedArabEmirates']
['18', 'Japan']
['11', 'Iran']
['87', 'SouthKorea']
['2', 'Australia']
['142', 'SouthKorea']
February  21
['366 ', ' Hubei']
['3', 'SouthKorea']
['12', 'Italy']
['7', 'UnitedStates']
['2', 'UnitedArabEmirates']
['2', 'Australia']
['3', 'Italy']
['12', 'Japan']
['13', 'Iran']
['2', 'Italy']
['11', 'UnitedStates']
['48', 'SouthKorea']
['2', 'Taiwan']
['3', 'Japan']
['45', 'SouthKorea']
February  20
['2', 'Australia']
['5', 'SouthKorea']
['10', 'Japan']
['3', 'Iran']
['22', 'SouthKorea']
['24', 'SouthKorea']
February  19
['5', 'SouthKorea']
['2', 'SouthKorea']
['3', 'Singapore']
['2', 'Iran']
['5', 'SouthKorea']
['10', 'Japan']
['15', 'SouthKorea']
February  18
['8', 'Japan']
['4', 'Singapore']
February  17
['2', 'Taiwan']
['2', 'HongKong']
['2', 'Singapore']
['4', 'Japan']
['2', 'Japan']
February  16
['3', 'Singapore']
['2', 'Taiwan']
['6', 'Japan']
February  15
['5', 'Singapore']
['8', 'Japan']
['2', 'Malaysia']
['3', 'Japan']
February  14
['4', 'Japan']
['2', 'Japan']
['3', 'HongKong']
['2', 'Japan']
February  13
['3', 'HongKong']
['8', 'Singapore']
['2', 'Japan']
['44', 'Japan']
February  12
['3', 'Singapore']
February  11
['39', 'Japan']
['2', 'Germany']
['2', 'Singapore']
['2', 'Japan']
February  10
['3', 'HongKong']
['2', 'Singapore']
['4', 'UK']
['65', 'Japan']
February  9
['3', 'Singapore']
February  8
['7', 'Singapore']
['5', 'France']
['3', 'Japan']
February  7
['41', 'Japan']
February  6
['2', 'Canada']
February  5
['2', 'Malaysia']
February  4
['6', 'Singapore']
['6', 'Thailand']
['2', 'Japan']

Extract Data for March

In [9]:
# Open the file with read only permit
f = open('March raw data.txt')

# use readline() to read the first line 
line = f.readline()
i=0

while line:
    
    line = line.strip()
    line = line.replace('[Source]','')
    p1 = '\d+ new cases in the \w+'
    p2 = '\d+ new cases in \w+'
    p3 = '\d+ new cases and \d+ new deaths in the \w+'
    p4 = '\d+ new cases and \d+ new deaths in \w+'
    p5 = '\d+ new death and \d+ new cases in the \w+'
    p6 = '\d+ new death and \d+ new cases in \w+'
    
    if re.findall('^March',line):
        print('March ', re.findall('[0-9]{1,2}', line)[0])
    elif re.findall(p1, line):
        print(re.split(' new cases in the ', re.findall(p1, line)[0]))
    elif re.findall(p2, line):
        print(re.split(' new cases in ', re.findall(p2, line)[0]))
    elif re.findall(p3, line):
        print(re.split(' new cases and \d+ new deaths in the ', re.findall(p3, line)[0]))
    elif re.findall(p4, line):
        print(re.split('new cases and \d+ new deaths in', re.findall(p4, line)[0]))
    elif re.findall(p5, line):
        newline = re.split(' new death and ', re.findall(p5, line)[0])[1]
        print(re.split(' new cases in the ', newline))
    elif re.findall(p6, line):
        newline = re.split(' new death and ', re.findall(p6, line)[0])[1]
        print(re.split(' new cases in ', newline))
        
    line = f.readline()
    
f.close()

March  11
['73', 'UK']
['313 ', ' Italy']
['4', 'Israel']
['10', 'Greece']
['238', 'Qatar']
['4', 'Cyprus']
['73', 'UK']
['5', 'Brunei']
['493 ', ' Spain']
['5', 'HongKong']
['6', 'Colombia']
['121', 'Netherlands']
['3', 'Slovakia']
['5', 'Poland']
['23', 'Slovenia']
['2', 'Latvia']
['12', 'Singapore']
['4', 'Iceland']
['34', 'Norway']
['6', 'Romania']
['18', 'Portugal']
['19', 'Finland']
['122', 'Sweden']
['2', 'Morocco']
['2', 'Albania']
['7', 'Indonesia']
['7', 'Serbia']
['79', 'Bahrain']
['16', 'Philippines']
['24', 'Austria']
['6', 'South']
['3', 'Kuwait']
['2', 'Maldives']
['6', 'Thailand']
['3', 'Queensland']
['2', 'South']
['4', 'New']
['3', 'Louisiana']
['5', 'Georgia']
['8', 'Florida']
['242', 'SouthKorea']
['3', 'Paraguay']
March  10
['391 ', ' Spain']
['61', 'Netherlands']
['3', 'Poland']
['3', 'Czech']
['65', 'Sweden']
['6', 'Slovenia']
['3', 'Belarus']
['2', 'Azerbaijan']
['881 ', ' Iran']
['8', 'Israel']
['4', 'Albania']
['4', 'Iceland']
['2', 'Portugal']
['8', 'Indonesia']
['5', 'Brazil']
['28', 'Belgium']
['15', 'UAE']
['3', 'Estonia']
['4', 'Sweden']
['2', 'North']
['5', 'Greece']
['2', 'Latvia']
['5', 'Finland']
['9', 'India']
['4', 'Kuwait']
['9', 'Philippines']
['3', 'Thailand']
['2', 'Finland']
['2', 'Serbia']
['6', 'California']
['2', 'Kentucky']
March  9
['33', 'King']
['4', 'Georgia']
['11', 'Israel']
['557 ', ' Spain']
['2', 'India']
['203 ', ' France']
['3', 'Russia']
['797 ', ' Italy']
['4', 'Portugal']
['2', 'Israel']
['3', 'Canada']
['55', 'Denmark']
['2', 'Oman']
['2', 'Iceland']
['7', 'Slovenia']
['14', 'UAE']
['2', 'United']
['39', 'Belgium']
['4', 'Poland']
['595 ', ' Iran']
['24', 'Bahrain']
['18', 'Malaysia']
['13', 'Indonesia']
['28 ', ' Japan']
['165 ', ' SouthKorea']
['4', 'Saudi']
March  8
['3', 'Kentucky']
['2', 'Tennessee']
['2', 'Maryland']
['15', 'Massachusetts']
['7', 'California']
['2', 'New']
['7', 'Oregon']
['16', 'New']
['2', 'New']
['14', 'Israel']
['2', 'Ireland']
['492 ', ' Italy']
['16', 'Norway']
['3', 'Russia']
['177 ', ' France']
['240', 'Germany']
['2', 'Romania']
['4', 'Philippines']
['6', 'Iraq']
['3', 'Qatar']
['3', 'Canada']
['3', 'Dominican']
['4', 'Lebanon']
['5', 'Iceland']
['7', 'Greece']
['6', 'India']
['4', 'Slovenia']
['5', 'Czech']
['7', 'Portugal']
['10', 'Vietnam']
['64', 'United']
['2', 'Kuwait']
['12', 'Singapore']
['42', 'Sweden']
['77', 'Netherlands']
['2', 'Hungary']
['8', 'Denmark']
['2', 'Poland']
['10', 'San']
['88 ', ' Spain']
['10', 'San']
['743 ', ' Iran']
['2', 'Australia']
['4', 'Saudi']
['4', 'Finland']
['2', 'Indonesia']
['5', 'India']
['2', 'Bulgaria']
['23', 'Austria']
['4', 'Costa']
['272 ', ' SouthKorea']
March  7
['5', 'Peru']
['116', 'UnitedStates']
['34', 'New']
['2', 'Pennsylvania']
['3', 'Florida']
['22 ', ' Washington']
['17', 'California']
['6', 'Colorado']
['4', 'Israel']
['21', 'Greece']
['6', 'Canada']
['296 ', ' France']
['33', 'Egypt']
['8', 'Iraq']
['247 ', ' Italy']
['6', 'Lebanon']
['3', 'San']
['130', 'Germany']
['124 ', ' Spain']
['5', 'Iceland']
['7', 'Portugal']
['5', 'Czech']
['3', 'Palestine']
['15', 'Austria']
['42', 'UK']
['6', 'Denmark']
['60', 'Netherlands']
['2', 'Saudi']
['24', 'Sweden']
['2', 'Romania']
['4', 'Slovenia']
['60', 'Belgium']
['25', 'Bahrain']
['3', 'India']
['3', 'Afghanistan']
['4', 'Finland']
['4', 'Georgia']
['076 ', ' Iran']
['2', 'Slovakia']
['10', 'Malaysia']
['3', 'Vietnam']
['2', 'Philippines']
['3', 'Kuwait']
['2', 'Thailand']
['2', 'Algeria']
['2', 'Switzerland']
['29', 'Norway']
['15', 'Japan']
['5', 'Brazil']
['448 ', ' SouthKorea']
['11', 'Australia']
March  6
['98', 'UnitedStates']
['9 ', ' Washington']
['11', 'Calfornia']
['5', 'Argentina']
['23', 'Austria']
['5', 'Ireland']
['2', 'North']
['9', 'Palestine']
['230 ', ' France']
['119 ', ' Spain']
['778 ', ' Italy']
['6', 'Lebanon']
['4', 'Israel']
['94', 'Switzerland']
['4', 'Poland']
['17', 'UnitedArabEmirates']
['3', 'Romania']
['3', 'Qatar']
['8', 'Iceland']
['6', 'Czeck']
['5', 'Scotland']
['4', 'Portugal']
['125', 'Germany']
['64 ', ' Spain']
['5', 'Bahrain']
['6', 'Russia']
['2', 'San']
['5', 'Brazil']
['3', 'Denmark']
['13', 'Singapore']
['14', 'Greece']
['3', 'Azerbaijan']
['12', 'Egypt']
['59', 'Belgium']
['234 ', ' Iran']
['28', 'Malaysia']
['5', 'Estonia']
['42', 'Sweden']
['2', 'Indonesia']
['3', 'Finland']
['56', 'Japan']
['2', 'Norway']
['2', 'Philippines']
['17', 'Canada']
March  5
['2', 'Hungary']
['138 ', ' France']
['7', 'Ireland']
['5', 'Brazil']
['283', 'Germany']
['5', 'addition']
['769 ', ' Italy']
['42', 'Sweden']
['5', 'Slovenia']
['5', 'Denmark']
['28', 'UK']
['2', 'Israel']
['3', 'Ecuador']
['4', 'Czech']
['3', 'Portugal']
['44', 'Netherlands']
['33', 'Japan']
['5', 'Republic']
['22', 'Greece']
['3', 'Saudi']
['9', 'Iceland']
['5', 'Malaysia']
['27', 'Belgium']
['3', 'Azebaijan']
['591 ', ' Iran']
['5', 'Finland']
['3', 'Scotland']
['2', 'Kuwait']
['11', 'Norway']
['15', 'Austria']
['4', 'Thailand']
March  4
['34', 'UnitedStates']
['12', 'Washington']
['9', 'New']
['12', 'California']
['4', 'Canada']
['3', 'Ecuador']
['4', 'Ireland']
['587 ', ' Italy']
['22', 'Sweden']
['59', 'Germany']
['73', 'France']
['36', 'UK']
['23', 'Norway']
['12', 'Iceland']
['15', 'Netherlands']
['5', 'Denmark']
['5', 'San']
['3', 'Czech']
['2', 'Greece']
['10', 'Belgium']
['2', 'Portugal']
['35', 'Switzerland']
['2', 'Belarus']
['2', 'Scotland']
['5', 'Austria']
['3', 'Oman']
['3', 'Iraq']
['2', 'Lebanon']
['3', 'Bahrain']
['3', 'Israel']
['2', 'Senegal']
['9', 'Algeria']
['2', 'Singapore']
['2', 'HongKong']
['38', 'Japan']
['14', 'Malaysia']
['22', 'India']
March  3
['3', 'Belarus']
['3', 'Canada']
['6', 'UnitedArabEmirates']
['3', 'Algeria']
['6', 'Denmark']
['2', 'Portugal']
['6', 'Sweden']
['5', 'Iraq']
['466 ', ' Italy']
['6', 'Austria']
['851 ', ' SouthKorea']
['2', 'Oman']
['2', 'Iceland']
['12', 'UK']
['2', 'Singapore']
['1', 'Croatia']
['2', 'San']
['5', 'Netherlands']
['7', 'Belgium']
['8', 'Norway']
['31', 'Germany']
['9', 'Sweden']
['28', 'Switzerland']
['6', 'Australia']
['2', 'Portugal']
['7', 'Malaysia']
['19', 'Japan']
['8', 'UnitedStates']
March  2
['22', 'UnitedStates']
['2', 'Israel']
['3', 'Canada']
['3', 'Iceland']
['335 ', ' Italy']
['6', 'Norway']
['2', 'Bahrain']
['4', 'Qatar']
['3', 'India']
['3', 'Lebanon']
['6', 'Austria']
['4', 'UK']
['36', 'Spain']
['8', 'Netherlands']
['6', 'Belgium']
['18', 'Japan']
['523 ', ' Iran']
['2', 'Iraq']
['6', 'Belgium']
['27', 'Germany']
['2', 'Spain']
['10', 'Kuwait']
['4', 'Australia']
March  1
['51', 'Germany']
['26', 'Spain']
['30', 'France']
['573 ', ' Italy']
['5', 'Finland']
['3', 'Netherlands']
['4', 'Austria']
['2', 'Norway']
['3', 'Israel']
['2', 'Qatar']
['6', 'Bahrain']
['6', 'Iraq']
['3', 'Lebanon']
['385 ', ' Iran']
['3', 'Algeria']
['4', 'Canada']
['5', 'UnitedStates']
['4', 'Malaysia']